export const WorkListActionTypes = {
  ADD_WORK_LIST_ITEM_START: "ADD_WORK_LIST_ITEM_START",
  ADD_WORK_LIST_ITEM_SUCCESS: "ADD_WORK_LIST_ITEM_SUCCESS",
  ADD_WORK_LIST_ITEM_FAILURE: "ADD_WORK_LIST_ITEM_FAILURE",
  FETCH_WORK_LIST_START: "FETCH_WORK_LIST_START",
  FETCH_WORK_LIST_SUCCESS: "FETCH_WORK_LIST_SUCCESS",
  FETCH_WORK_LIST_FAILURE: "FETCH_WORK_LIST_FAILURE",
  UPDATE_WORK_LIST_ITEM_START: "UPDATE_WORK_LIST_ITEM_START",
  UPDATE_WORK_LIST_ITEM_SUCCESS: "UPDATE_WORK_LIST_ITEM_SUCCESS",
  UPDATE_WORK_LIST_ITEM_FAILURE: "UPDATE_WORK_LIST_ITEM_FAILURE",
  DELETE_WORK_LIST_ITEM_START: "DELETE_WORK_LIST_ITEM_START",
  DELETE_WORK_LIST_ITEM_SUCCESS: "DELETE_WORK_LIST_ITEM_SUCCESS",
  DELETE_WORK_LIST_ITEM_FAILURE: "DELETE_WORK_LIST_ITEM_FAILURE",
};
