export const PartsCatalogActionTypes = {
    FETCH_PARTS_CATALOG_START: "FETCH_PARTS_CATALOG_START",
    FETCH_PARTS_CATALOG_SUCCESS: "FETCH_PARTS_CATALOG_SUCCESS",
    FETCH_PARTS_CATALOG_FAILURE: "FETCH_PARTS_CATALOG_FAILURE",
    ADD_PARTS_CATALOG_START: "ADD_PARTS_CATALOG_START",
    ADD_PARTS_CATALOG_SUCCESS: "ADD_PARTS_CATALOG_SUCCESS",
    ADD_PARTS_CATALOG_FAILURE: "ADD_PARTS_CATALOG_FAILURE",
    UPDATE_PARTS_CATALOG_START: "UPDATE_PARTS_CATALOG_START",
    UPDATE_PARTS_CATALOG_SUCCESS: "UPDATE_PARTS_CATALOG_SUCCESS",
    UPDATE_PARTS_CATALOG_FAILURE: "UPDATE_PARTS_CATALOG_FAILURE",
    DELETE_PARTS_CATALOG_START: "DELETE_PARTS_CATALOG_START",
    DELETE_PARTS_CATALOG_SUCCESS: "DELETE_PARTS_CATALOG_SUCCESS",
    DELETE_PARTS_CATALOG_FAILURE: "DELETE_PARTS_CATALOG_FAILURE",
}