export const DispatcherActionTypes = {
  FETCH_DISPATCHERS_START: "FETCH_DISPATCHERS_START",
  FETCH_DISPATCHERS_SUCCESS: "FETCH_DISPATCHERS_SUCCESS",
  FETCH_DISPATCHERS_FAILURE: "FETCH_DISPATCHERS_FAILURE",
  ADD_DISPATCHER_START: "ADD_DISPATCHER_START",
  ADD_DISPATCHER_SUCCESS: "ADD_DISPATCHER_SUCCESS",
  ADD_DISPATCHER_FAILURE: "ADD_DISPATCHER_FAILURE",
  UPDATE_DISPATCHER_START: "UPDATE_DISPATCHER_START",
  UPDATE_DISPATCHER_SUCCESS: "UPDATE_DISPATCHER_SUCCESS",
  UPDATE_DISPATCHER_FAILURE: "UPDATE_DISPATCHER_FAILURE",
  DELETE_DISPATCHER_START: "DELETE_DISPATCHER_START",
  DELETE_DISPATCHER_SUCCESS: "DELETE_DISPATCHER_SUCCESS",
  DELETE_DISPATCHER_FAILURE: "DELETE_DISPATCHER_FAILURE",
};
