export const TechnicianActionTypes = {
  FETCH_TECHNICIANS_START: "FETCH_TECHNICIANS_START",
  FETCH_TECHNICIANS_SUCCESS: "FETCH_TECHNICIANS_SUCCESS",
  FETCH_TECHNICIANS_FAILURE: "FETCH_TECHNICIANS_FAILURE",
  ADD_TECHNICIAN_START: "ADD_TECHNICIAN_START",
  ADD_TECHNICIAN_SUCCESS: "ADD_TECHNICIAN_SUCCESS",
  ADD_TECHNICIAN_FAILURE: "ADD_TECHNICIAN_FAILURE",
  UPDATE_TECHNICIAN_START: "UPDATE_TECHNICIAN_START",
  UPDATE_TECHNICIAN_SUCCESS: "UPDATE_TECHNICIAN_SUCCESS",
  UPDATE_TECHNICIAN_FAILURE: "UPDATE_TECHNICIAN_FAILURE",
  DELETE_TECHNICIAN_START: "DELETE_TECHNICIAN_START",
  DELETE_TECHNICIAN_SUCCESS: "DELETE_TECHNICIAN_SUCCESS",
  DELETE_TECHNICIAN_FAILURE: "DELETE_TECHNICIAN_FAILURE",
};
