export const LabelActionTypes = {
  ADD_LABEL_START: "ADD_LABEL_START",
  ADD_LABEL_SUCCESS: "ADD_LABEL_SUCCESS",
  ADD_LABEL_FAILURE: "ADD_LABEL_FAILURE",
  FETCH_LABEL_START: "FETCH_LABEL_START",
  FETCH_LABEL_SUCCESS: "FETCH_LABEL_SUCCESS",
  FETCH_LABEL_FAILURE: "FETCH_LABEL_FAILURE",
  UPDATE_LABEL_START: "UPDATE_LABEL_START",
  UPDATE_LABEL_SUCCESS: "UPDATE_LABEL_SUCCESS",
  UPDATE_LABEL_FAILURE: "UPDATE_LABEL_FAILURE",
  DELETE_LABEL_START: "DELETE_LABEL_START",
  DELETE_LABEL_SUCCESS: "DELETE_LABEL_SUCCESS",
  DELETE_LABEL_FAILURE: "DELETE_LABEL_FAILURE",
};
