export const InventoryContainersActionTypes = {
    FETCH_INVENTORY_CONTAINERS_START: "FETCH_INVENTORY_CONTAINERS_START",
    FETCH_INVENTORY_CONTAINERS_SUCCESS: "FETCH_INVENTORY_CONTAINERS_SUCCESS",
    FETCH_INVENTORY_CONTAINERS_FAILURE: "FETCH_INVENTORY_CONTAINERS_FAILURE",
    ADD_INVENTORY_CONTAINERS_START: "ADD_INVENTORY_CONTAINERS_START",
    ADD_INVENTORY_CONTAINERS_SUCCESS: "ADD_INVENTORY_CONTAINERS_SUCCESS",
    ADD_INVENTORY_CONTAINERS_FAILURE: "ADD_INVENTORY_CONTAINERS_FAILURE",
    UPDATE_INVENTORY_CONTAINERS_START: "UPDATE_INVENTORY_CONTAINERS_START",
    UPDATE_INVENTORY_CONTAINERS_SUCCESS: "UPDATE_INVENTORY_CONTAINERS_SUCCESS",
    UPDATE_INVENTORY_CONTAINERS_FAILURE: "UPDATE_INVENTORY_CONTAINERS_FAILURE",
    DELETE_INVENTORY_CONTAINERS_START: "DELETE_INVENTORY_CONTAINERS_START",
    DELETE_INVENTORY_CONTAINERS_SUCCESS: "DELETE_INVENTORY_CONTAINERS_SUCCESS",
    DELETE_INVENTORY_CONTAINERS_FAILURE: "DELETE_INVENTORY_CONTAINERS_FAILURE"
}