export const InvoiceActionTypes = {
    FETCH_INVOICES_START: "FETCH_INVOICES_START",
    FETCH_INVOICES_SUCCESS: "FETCHINVOICES_SUCCESS",
    FETCH_INVOICES_FAILURE: "FETCH_INVOICES_FAILURE",
    ADD_INVOICES_START: "ADD_INVOICES_START",
    ADD_INVOICES_SUCCESS: "ADD_INVOICES_SUCCESS",
    ADD_INVOICES_FAILURE: "ADD_INVOICES_FAILURE",
    UPDATE_INVOICES_START: "UPDATE_INVOICES_START",
    UPDATE_INVOICES_SUCCESS: "UPDATE_INVOICES_SUCCESS",
    UPDATE_INVOICES_FAILURE: "UPDATE_INVOICES_FAILURE",
    DELETE_INVOICES_START: "DELETE_INVOICES_START",
    DELETE_INVOICES_SUCCESS: "DELETE_INVOICES_SUCCESS",
    DELETE_INVOICES_FAILURE: "DELETE_INVOICES_FAILURE"
}