export const ClientsActionTypes = {
  FETCH_CLIENTS_START: "FETCH_CLIENTS_START",
  FETCH_CLIENTS_SUCCESS: "FETCH_CLIENTS_SUCCESS",
  FETCH_CLIENTS_FAILURE: "FETCH_CLIENTS_FAILURE",
  ADD_CLIENT_START: "ADD_CLIENT_START",
  ADD_CLIENT_SUCCESS: "ADD_CLIENT_SUCCESSS",
  ADD_CLIENT_FAILURE: "ADD_CLIENT_FAILURE",
  UPDATE_CLIENT_START: "UPDATE_CLIENT_START",
  UPDATE_CLIENT_SUCCESS: "UPDATE_CLIENT_SUCCESS",
  UPDATE_CLIENT_FAILURE: "UPDATE_CLIENT_FAILURE",
  DELETE_CLIENT_START: "DELETE_CLIENT_START",
  DELETE_CLIENT_SUCCESS: "DELETE_CLIENT_SUCCESS",
  DELETE_CLIENT_FAILURE: "DELETE_CLIENT_FAILURE",
};
