export const PaymentActionTypes = {
  ADD_PAYMENT_START: "ADD_PAYMENT_START",
  ADD_PAYMENT_SUCCESS: "ADD_PAYMENT_SUCCESS",
  ADD_PAYMENT_FAILURE: "ADD_PAYMENT_FAILURE",
  FETCH_PAYMENTS_START: "FETCH_PAYMENTS_START",
  FETCH_PAYMENTS_SUCCESS: "FETCH_PAYMENTS_SUCCESS",
  FETCH_PAYMENTS_FAILURE: "FETCH_PAYMENTS_FAILURE",
  UPDATE_PAYMENT_START: "UPDATE_PAYMENT_START",
  UPDATE_PAYMENT_SUCCESS: "UPDATE_PAYMENT_SUCCESS",
  UPDATE_PAYMENT_FAILURE: "UPDATE_PAYMENT_FAILURE",
  DELETE_PAYMENT_START: "DELETE_PAYMENT_START",
  DELETE_PAYMENT_SUCCESS: "DELETE_PAYMENT_SUCCESS",
  DELETE_PAYMENT_FAILURE: "DELETE_PAYMENT_FAILURE",
};
